/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    CartComponent: typeof import('./components/cart/cartComponent.vue')['default']
    CheckoutBox: typeof import('./components/cart/CheckoutBox.vue')['default']
    ContactInfo: typeof import('./components/checkout/ContactInfo.vue')['default']
    copy: typeof import('./components/AppFooter copy.vue')['default']
    Footer: typeof import('./components/home/Footer.vue')['default']
    Header: typeof import('./components/home/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HorizontalProduct: typeof import('./components/cards/HorizontalProduct.vue')['default']
    PopularProducts: typeof import('./components/home/PopularProducts.vue')['default']
    ProductList: typeof import('./components/cart/ProductList.vue')['default']
    Review: typeof import('./components/checkout/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShippingInfo: typeof import('./components/checkout/ShippingInfo.vue')['default']
    TopNavbar: typeof import('./components/TopNavbar.vue')['default']
    VerticalProduct: typeof import('./components/cards/VerticalProduct.vue')['default']
  }
}
